# [Info]
site_name: 欢迎光~~临
site_url: https://chenwp5.github.io/blog/
site_author: chenwp5
# [github]
repo_name: chenwp5/blog
repo_url: https://github.com/chenwp5/blog
# [版权]
copyright: Copyright &copy; 2023-2023陈伟平 # 左下角的版权声明
# [UI]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: white # 上方的
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features: 
    - navigation.instant #- header.autohide  #自动隐藏
    #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    #- navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮
  language: zh # 一些提示性的文字会变成中文
  icon: 
    repo: fontawesome/brands/github #指定右上角图标为github


# [插件]
plugins:
  - blog:
      enabled: true
  - search: 
      enabled: true # false:会显示搜索框，但功能不可用
      lang: zh #支持中文搜索
  - tags:
      tags_file: tags.md #网上搜来的，通过标签实现文档列表，用法不对，后续得修改

extra:
  generator: true  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/github
      link: https://chenwp5.github.io/blog/
    - icon: fontawesome/brands/weixin
      link: zanwu
  
  analytics: 
    provider: google
    property: G-TPQYN8G7TM # Google Analytics ID
    feedback:
      title: 此页面是否对你有帮助吗？
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            谢谢你的反馈！
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >- 
            谢谢你的反馈，如果发现什么问题请联系我，我会尽快回复您
  consent:
    title: Cookie consent
    description: >- 
      我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
      如果你同意,你可以帮助我们让我们的网站更好。


markdown_extensions:
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
     
#extra_javascript:
  #- javascripts/extra.js
  #- javascripts/mathjax.js
  #- https://polyfill.io/v3/polyfill.min.js?features=es6
  #- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#extra_css:
  #- stylesheets/extra.css
 
# [Navigtion]
nav:
  - 数据库:
    - MySQL:
      - MySQL知识: mysql\MySQL.md
      - MySQL技术规范: mysql\MySQL技术规范.md
  - GIT:
    - Git知识总结: git\Git知识总结.md
    - Git交互式暂存: git\Git交互式暂存.md
  - 工具:
    - mkdocs
  - 博客:
    - blog/index.md