site_name: 后花园
repo_url: https://github.com/chenwp5/sansi
repo_name: chenwp/sansi

##目录设置
nav:
  - 数据库: 
    - MySql:
      - InnoDB版本及新特性: database/mysql/InnoDB版本及新特性.md
      - InnoDB存储引擎:
        - InnoDB磁盘结构: database/mysql/InnoDB磁盘结构.md
        - InnoDB缓冲池: database/mysql/InnoDB缓冲池.md
      - MySQL查询原理: database/mysql/MySQL查询原理.md
      - MySQL执行计划: database/mysql/MySQL执行计划.md
      - MySQL事务: database/mysql/MySQL事务.md
  - Spring: 
    - Spring源码记录: spring/Spring源码记录.md
  - GIT:
    - Git交互式暂存: git/Git交互式暂存.md
    - Git知识总结: git/Git知识总结.md
  - 工具:
    - mkdocs建站: mkdocs/mkdocs搭建记录.md
  - 博客:
    - blog/index.md

#设置博客
plugins:
  - blog
  - search

#主题设置
theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github-alt
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 切换到浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 切换到系统自适应模式
  features:
    - toc.follow
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - search.highlight
    - search.suggest

#Cookie管理
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  #google analytics
  analytics:
    provider: google
    property: G-0XF6Z1SSY8
    feedback:
      title: 这篇文章是否对您有帮助?
      ratings:
        - icon: material/heart
          name: 有那么一点帮助~
          data: 5
          note: >-
            感谢您的反馈！
        - icon: material/heart-broken
          name: 没啥帮助~
          data: 1
          note: >- 
            OKOK，好好好！
